version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - run:
          command: sh build.sh

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build